### ISSUE TITLE
TypeError: Object doesn't support property or method 'asinh' 

### ISSUE THREAD

**Issue by jguecaimburu** [mercadopago/sdk-js#12]
**Describe the bug**

IE11 users see this error message in their console:
```js
TypeError: Object doesn't support property or method 'asinh' 
```

**To Reproduce**

We are including the sdk in our layout as:
```html
<script src="https://secure.mlstatic.com/sdk/javascript/v1/mercadopago.js"></script>
```
We use Rollbar to report bugs and are seeing this error with the following traceback:
```js
TypeError: El objeto no acepta la propiedad o el método 'asinh' (Most recent call first)
File Unknown script code line 23 col 390 in window.mlbp.U
File Unknown script code line 19 col 421 in window.mlbp.L
File Unknown script code line 52 col 85 in window.mlbp.K
File Unknown script code line 61 col 133 in x
File Unknown script code line 61 col 397 in Global code
File https://secure.mlstatic.com/sdk/javascript/v1/mercadopago.js
line 1 col 24179 in success
File https://secure.mlstatic.com/sdk/javascript/v1/mercadopago.js
line 1 col 10208 in a.onreadystatechange
```

**Expected behavior**

We expected no error message. Are we unable to charge customers that use IE11?

**Environment:**

This happens to every user in IE11

**Comment by NicholasPedroso** [comment]
Hi @jguecaimburu ,

Seems like you are using and outdated version of MercadoPago.js
We strongly recommend you to use our [last version](https://sdk.mercadopago.com/js/v2) which has support for IE11.

[Checkout our documentation](https://www.mercadopago.com.br/developers/en/guides/online-payments/checkout-api/v2/receiving-payment-by-card),

Thanks

**Comment by jguecaimburu** [comment]
Thanks for the quick reply @NicholasPedroso!

I believe this should be updated also here: https://www.mercadopago.com.co/developers/en/guides/sdks
IE11 seems to be supported by v1 as well.

**Comment by NicholasPedroso** [comment]
Hi,

There is a dropdown with version 2.

we apologize that it was not possible to notice before.
I will send this feedback to the UX team :)

![image](https://user-images.githubusercontent.com/8353990/114606956-54551900-9c72-11eb-9c5e-6c2ec94b9973.png)

**Comment by jguecaimburu** [comment]
We noticed that. It's just that IE11 appears as supported in both versions :see_no_evil:, that was the confusing part. 
![2021-04-13-162226_795x417_scrot](https://user-images.githubusercontent.com/56755880/114608780-6df76000-9c74-11eb-90ed-a54747161a72.png)
![2021-04-13-162217_535x236_scrot](https://user-images.githubusercontent.com/56755880/114608786-6e8ff680-9c74-11eb-8ff9-9c400f97250f.png)

Thanks for all your help.
