### ISSUE TITLE
Iniciar Brick con documento no funciona siempre

### ISSUE THREAD

**Issue by artmadeit** [mercadopago/sdk-js#138]
**Describe the bug**
En la documentación de card payment de Checkout Bricks
https://www.mercadopago.com.pe/developers/es/docs/checkout-bricks/card-payment-brick/additional-customization/initialize-data-on-the-bricks

Indica: "Cuando se envía un número de identificación válido y un tipo de identificación correspondiente, el campo del documento del pagador ya está automaticamente completado."

Sin embargo esto no siempre ocurre

**To Reproduce**
Entrar a https://www.mercadopago.com.pe/developers/es/live-demo/card-payment-brick

- Con pais de operacion Peru
- Completar Configurar inicialización del Brick en Avanzado, luego con DNI funciona
![image](https://user-images.githubusercontent.com/18428325/222925906-8ebf82cb-65c3-48da-aab5-aeaea0cfd0fd.png)

pero con RUC falla (otros documentos pasa lo mismo)
![image](https://user-images.githubusercontent.com/18428325/222926031-9d5ed868-53e1-4a80-9eb3-2b0423f71d94.png)

Si se hace lo mismo con algun codigo de ejemplo basico falla.

**Expected behavior**
Cuando se envía un número de identificación válido y un tipo de identificación correspondiente, el campo del documento del pagador **no se completa** automaticamente como indica en la documentación esto sucde con tipos de identificación RUC (entre otros)

**Environment (please complete the following information):**

- Browser: Chrome
Supongo falla en todos los browsers

**Comment by icaldana** [comment]
Hola @artmadeit, como está?

Sentimos mucho las molestias ocasionadas. Gracias por informar este problema, estamos investigando y tomando medidas para solucionarlo.

Gracias.

**Comment by icaldana** [comment]
@artmadeit hello! The fix was deployed and it is already available! 😄 
Thank you!

**Comment by artmadeit** [comment]
Thanks 👍
