### ISSUE TITLE
Installment fields not showing

### ISSUE THREAD

**Issue by imonzalvo** [mercadopago/sdk-js#141]
**Describe the bug**
The installments field is not showing no matter which customization object I pass to the brick for card_payment brick.

It is also not working on the docs demo:
https://www.mercadopago.com.uy/developers/es/live-demo/card-payment-brick

**Comment by icaldana** [comment]
Hello @imonzalvo!

Thank you for reporting this problem, we do apologize for the inconvenience. We will prioritize this issue and let you know once it is fixed.

Thank you!

**Comment by imonzalvo** [comment]
@icaldana Just figured out what the problem was. In order for this field to show, the user must configure their account to accept installments.

**Comment by icaldana** [comment]
> @icaldana Just figured out what the problem was. In order for this field to show, the user must configure their account to accept installments.

Wow, I am glad you figured that out! But anyway, sorry for not have replied sooner to you.
