### ISSUE TITLE
Error: Missing melidata tracking component - [name:melidata] [level:INFO]

### ISSUE THREAD

**Issue by charliezstong** [mercadopago/sdk-js#17]
Hola, tengo el siguiente error:

[Report Only] Refused to frame 'https://www.mercadopago.com.pe/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' *.mercadolibre.com".

Actualmente renderiza el botón de pago, pero al cargar esta dando el anterior error en la consola, el código es:

<div class="cho-container"></div>

    <script src="https://sdk.mercadopago.com/js/v2"></script>
    <script>
        const mp = new MercadoPago('TEST-xxxx-xxxxxxxxx-xxxxxx', {
            locale: 'es-PE'
        })
        const checkout = mp.checkout({
            preference: {
                id: 'xxxxxxxxxx'
            }
        });
        checkout.render({
            container: '.cho-container',
            label: 'Pagar con Mercadopago'
        });
    </script>

**Comment by Kneehole** [comment]
Muchas gracias @charliezstong por el reporte, vamos a estar revisando este inconveniente y dandote feedback!

**Comment by charliezstong** [comment]
@Kneehole Ya me funciono, era error de mi lado del preference Id. (Tal vez me hubiera dado luz, si me hubiera mandado un mensaje que el preference Id estaba mal)
Sorry

**Comment by markes41** [comment]
Hola, buenas. Qué problema tenías con el preference Id? Tengo el mismo error y no sabría bien qué va en ese campo del script.

**Comment by LucasLazogue** [comment]
Buenas, como pudiste solucionarlo?
Me tira exactamente el mismo error

**Comment by Kneehole** [comment]
Buenas @markes41 y @LucasLazogue, el mensaje:  `[Report Only] Refused to frame 'https://www.mercadopago.com.pe/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' *.mercadolibre.com".` no es un error. Como indica el tag, es un warning que envía el browser.

En el caso de ustedes:
* Están pudiendo generar la preferencia de pago con datos simples? como el indicado en el punto [1.2 de la integración de Checkout Pro](https://www.mercadopago.com.ar/developers/en/guides/online-payments/checkout-pro/integration#bookmark_steps_to_integrate)?

* Están poniendo correctamente el id en la preferencia y en la jerarquía necesaria en el snippet de Frontend? como se indica en el punto [2.2 de la misma documentación](https://www.mercadopago.com.ar/developers/en/guides/online-payments/checkout-pro/integration#bookmark_steps_to_integrate)?

En caso afirmativo les pido si por favor nos pueden acercar sus snippets con las credenciales ofuscadas

**Comment by JaraClaudioEz** [comment]
Buenas. Tengo la misma advertencia en consola, cómo se soluciona? La diferencia que la preferencia la estoy generando con un par de datos más a los indicados en el punto 1.2, estoy agregando la referencia externa, notification_url, back_urls, auto_return y datos del payer. Se agradece respuesta.

**Comment by PorotoX** [comment]
Yo lo solucioné así:
```
// Agrega credenciales de SDK
		const mp = new MercadoPago('TEST-*****', {
		locale: 'es-UY'
		});

		// Inicializa el checkout
		mp.checkout({
			preference: {
				id: '<?php echo $preference->id; ?>'
			},
			render: {
			container: '.pagar', // Indica dónde se mostrará el botón de pago
			label: 'Pagar la compra', // Cambia el texto del botón de pago (opcional)
			}
});
```

**Comment by charliezstong** [comment]
Hola gente, esto no es más que un error en el **preference id que se genera en el backend**. 
No estoy 100% pero creo que era porque estaba reutilizando un mismo preference ID más de una vez, @Kneehole corrígeme si me equivoco. 

Tal vez mercadopago en vez de ese warning si enviara un mensaje del "error" seria más claro para todos 🤔 ya que es un error en el preference ID que estan colocando. 

@PorotoX Se te soluciono ya que se genera desde php un render hacia el front con un nuevo preference ID automático, en el caso de aquellos que colocan un preference id de forma manual generado con cualquier SDK en el backend y luego lo llaman desde javascript, simplemente generen un preference id diferente en las pruebas o hagan un fetch hacia sus backend para que el preference ID sea diferente en cada petición, al parecer es la solución.

**Comment by josephzakzuk** [comment]
Buenas también tengo un problema al intentar integrar mercadopago, la cuestión es que cuando oprimo el botón pagar, no me muestra las opciones de pago sino que enseguida me pide autenticación, al autenticarme con la cuenta de prueba que genere, solo me dice que no tiene dinero y ya }, no me permite seleccionar por ejemplo tarjetas de crédito para realizar la compra de prueba, cualquier ayuda seria de verdad apreciable, gracias.
![pago](https://user-images.githubusercontent.com/58088870/124320604-cc303280-db41-11eb-9aa5-313d616cb345.png)

**Comment by hdlopez** [comment]
Hola @josephzakzuk ! 

Lo que me imagino que puede sucederte es que en la preferencia de pago, estes configurando el "purpose" wallet_purchase ([link a docu](https://www.mercadopago.com.ar/developers/es/guides/online-payments/checkout-api/wallet-integration)). Eso le indica a MP que solo debe aceptar pagos con la billetera de MP.

Dicho eso es importante mencionar que este canal es solo para issues espécificos o feature request del sdk js. Cierro el issue.

Muchas gracias

**Comment by alemdg** [comment]
**sigue dando el mismo error:**

QUE MAS HAY QUE CONFIGURAR?, la documentacion es incorrecta o incompleta?



[Report Only] Refused to frame 'https://www.mercadopago.com.ar/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' *.mercadolibre.com".

browser.js:49 Missing melidata tracking component - [name:melidata] [level:INFO]
`

// Crea el objeto de request de la preference
            var request = new PreferenceRequest
            {
                Items = new List<PreferenceItemRequest>
                {
                    new PreferenceItemRequest
                    {
                        Title = "Mi producto",
                        Quantity = 1,
                        CurrencyId = "ARS",
                        UnitPrice = 12.27m,
                    },
                },
                BackUrls = new PreferenceBackUrlsRequest()
                {
                    Success = "http://5c34a7f7a44e.ngrok.io",
                    Failure = "http://5c34a7f7a44e.ngrok.io",
                    Pending = "http://5c34a7f7a44e.ngrok.io"
                }
            };
`

**Comment by maurerarthur** [comment]
Lo Checkout Pro que implementé funcionaba normalmente y simplemente dejó de funcionar hace 1 mes debido a este error. Esto sucede con Checkout Pro v1 y v2, ambos tienen el mismo error.

Alguien ya sabe cómo solucionarlo?

Gracias.

**Comment by manuelgomez7193** [comment]
Me pasa el mismo error, tenia un codigo escrito con check out pro y ahora me dejo de funcionar, me tira ese mismo error. 
![image](https://user-images.githubusercontent.com/62960259/125731243-bdf01798-b738-473c-9778-9380f30dd49a.png)

`// SDK de Mercado Pago
require __DIR__ .  '/vendor/autoload.php';
// Agrega credenciales
MercadoPago\SDK::setAccessToken('TEST-*******');`

`// Create a preference item
$item = new MercadoPago\Item();
$item->title = 'My Item';
$item->quantity = 1;
$item->unit_price = 10;
$preference->items = array($item);
$preference->save();`

`<script src="https://sdk.mercadopago.com/js/v2"></script>
<script>
// Agrega credenciales de SDK
  const mp = new MercadoPago('TEST-*****', {
        locale: 'es-UY'
  });

  // Inicializa el checkout
  mp.checkout({
      preference: {
          id: '<?php echo $preference->id; ?>'
      },
      render: {
            container:'.test123', // Indica dónde se mostrará el botón de pago
            label:'Pagar', // Cambia el texto del botón de pago (opcional)
      }
});
</script>`

**Comment by Emmaqm** [comment]
Buenas! Estoy teniendo el mismo error. Probé tanto con el SDK v1, cómo el SDK v2. Hace unos meses estaba funcionando correctamente y ahora dejó de funcionar.  Les agradezco si pueden comunicar algún tipo de solución. Gracias!

**Comment by Kneehole** [comment]
Buenas, recordamos nuevamente que este issue cerrado no corresponde a un error activo. El mensaje de consola corresponde a un log en consola auditable de la sdk en la integración inicial. 
No obstante, las pantallas que compartieron en su mayoría se asocian a una des regulación del estado de sus cuentas como vendedores. Por favor validen sus identidades en su cuenta de Mercado Pago para poder continuar operando normalmente

Saludos!

**Comment by maurerarthur** [comment]
> Buenas, recordamos nuevamente que este issue cerrado no corresponde a un error activo. El mensaje de consola corresponde a un log en consola auditable de la sdk en la integración inicial.
> No obstante, las pantallas que compartieron en su mayoría se asocian a una des regulación del estado de sus cuentas como vendedores. Por favor validen sus identidades en su cuenta de Mercado Pago para poder continuar operando normalmente
> 
> Saludos!

@Kneehole Pero cómo explicar que las implementaciones funcionaron normalmente y simplemente dejaron de funcionar?

**Comment by Kneehole** [comment]
> > Buenas, recordamos nuevamente que este issue cerrado no corresponde a un error activo. El mensaje de consola corresponde a un log en consola auditable de la sdk en la integración inicial.
> > No obstante, las pantallas que compartieron en su mayoría se asocian a una des regulación del estado de sus cuentas como vendedores. Por favor validen sus identidades en su cuenta de Mercado Pago para poder continuar operando normalmente
> > Saludos!
> 
> @Kneehole Pero cómo explicar que las implementaciones funcionaron normalmente y simplemente dejaron de funcionar?

La implementación no es que haya dejado de funcionar, dado que el mensaje indicado es que el vendedor no puede recibir pagos por el momento. Esto puede estar asociado a algún cambio regulatorio en tu país o tu cuenta donde debas seguir algún proceso de validación para poder continuar operando.

Saludos!

**Comment by maurerarthur** [comment]
Estaba haciendo más pruebas y confirmé que este problema ocurre en Google Chrome, pero funciona normalmente en Firefox, por lo que la implementación es correcta y los procesos de validación de la cuenta también son correctos. Esto parece ser un problema de Mercadopago.

**Comment by Mersmith** [comment]
> @Kneehole Ya me funciono, era error de mi lado del preference Id. (Tal vez me hubiera dado luz, si me hubiera mandado un mensaje que el preference Id estaba mal) Sorry

Como solucionaste el problema? tengo el mismo error.

**Comment by Esquirish** [comment]
No puedo hacer funcionar la integración minima del checkout pro:

Me aparece el mensaje en la consola de chrome: 

> [Report Only] Refused to frame 'https://www.mercadopago.com.pe/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' *.mercadolibre.com".

Que claramente indica que no permite cargar la pagina de pago en el modal. En su lugar carga la pagina de pago en una nueva pestaña. El comportamiento esperado es que la pagina de pago cargue en el mismo modal de mi página.

Nota: Mi cuenta de mercadopago no cuenta con ninguna restriccion o mis configuracion como mencionado en mensajes anteriores.

![2021-11-06_020122](https://user-images.githubusercontent.com/19341949/140601118-906cce01-2540-4a49-81ed-85267bbef05b.png)

**Comment by OscarJVD** [comment]
Esto solo funciona en https? Me tiene hasta los huevos, los init_point no corren y sale que intenta mas tarde :l

**Comment by OscarJVD** [comment]
Probaré la integración por API en mi app React

**Comment by estefaniadiazartucio** [comment]
@Esquirish Respondido en https://github.com/mercadopago/sdk-js/issues/37#issuecomment-964466700

Cualquier otra inconveniencia con la integración pueden pedir asistencia a través de https://www.mercadopago.com.ar/developers/es/support
