### ISSUE TITLE
Help me type the library for React js

### ISSUE THREAD

**Issue by s4mukka** [mercadopago/sdk-js#19]
Hello, I created a library in react to facilitate the use of sdk's js from the mercadopago, but I needed help with typing because I'm not sure what the official typing is. can you help me?
I believe that the library will be very useful for the community.
The project link is: https://github.com/s4mukka/react-sdk-mercadopago
It is my first library, so it may not be written in the best way.
Thanks!

**Comment by NicholasPedroso** [comment]
Hey @s4mukka how are you doing?

Thanks for helping our community, I'm sure it will be very useful for everyone.
Anyway, I'm going to close this thread since it's not an issue.

Feel free to bring this theme to [Discussions](https://github.com/mercadopago/sdk-js/discussions) 😉

Thanks
