### ISSUE TITLE
CheckOut Tokenize locale is omitted

### ISSUE THREAD

**Issue by ponyesteves** [mercadopago/sdk-js#20]
On the `Checkout tokenizer` implementation I've found I can't use a custom local. It always uses the locale from the Sellers country. If the seller is from Argentina it will show the checkout in 'es-AR' no matter I set  `en-US`. The same happens if I change the config and use Brasilian credentials it will show the checkout on `pt-BR`.

**To Reproduce**

```js
  function openCheckOut(settings) {
    const checkout = mercadoPagoCheckout(settings)
    checkout.open()
  }

  function mercadoPagoCheckout(settings) {
    // hardcoded local to `en-US` to illustrate the example
    const mp = new MercadoPago(settings.publicKey, { locale: 'en-US' })

    return mp.checkout({ tokenizer: buildTokenizer(settings) })
  }
```

**Expected behavior**
I expect that the widget content is shown on the locale we passed as an option when we instantiate `new MercadoPago(settings.publicKey, { locale: 'en-US' })`
 
**Environment (please complete the following information):**

- Browser: Chrome

**Comment by estefaniadiazartucio** [comment]
Hi @ponyesteves ! 
Thank you for reporting this issue.
The `locale` param used when initializing the SDK is optional and not supported by the checkout or tokenizer which, like you've said, set their locale based on the seller's country
