### ISSUE TITLE
Error de Sintaxis en Internet Explorer 11

### ISSUE THREAD

**Issue by davidromero55** [mercadopago/sdk-js#23]
**Describe the bug**
En explorer 11 no se muestra el botón de pago.
Error de sintaxis v2 (1,1983).

**To Reproduce**
Mostrar un boton de pago en explorer 11

- Test case to reproduce the bug.  Try to reproduce in the latest version.
- Code sample that fails
&lt;script src="https://sdk.mercadopago.com/js/v2"&gt;&lt;/script&gt;
--
&nbsp; | &lt;br&gt;&lt;br&gt;&lt;center&gt;
&nbsp; | &lt;h4&gt;Da clic en "Pagar" para realizar tu pago.&lt;/h4&gt;
&nbsp; | &lt;div id="mp-btn-scc"&gt;&lt;/div&gt;
&nbsp; | &lt;br/&gt;
&nbsp; | &lt;script&gt;
&nbsp; | const mp = new MercadoPago('APP_USR-*****', { locale: 'es-MX' });
&nbsp; | mp.checkout({
&nbsp; | preference: {
&nbsp; | id: '717212790-7656e52f-5235-4691-8446-2c5f1c741ffa'
&nbsp; | },
&nbsp; | render: {
&nbsp; | container: '#mp-btn-scc', // Indica dónde se mostrará el botón de pago
&nbsp; | label: 'Pagar', // Cambia el texto del botón de pago (opcional)
&nbsp; | }
&nbsp; | });
&nbsp; | &lt;/script&gt;

**Expected behavior**
En exploerer 11 no se muestra el botón

**Environment (please complete the following information):**

- Browser: IE11

**Comment by Kneehole** [comment]
Hola @davidromero55 muchas gracias por levantar el ticket! Pudimos reproducir el caso, te mantenemos informado

**Comment by estefaniadiazartucio** [comment]
Hola @davidromero55! 
Detectamos que había un problema con el CDN y no se estaba generando la versión con polyfills para IE11. 
Ya realizamos el fix respectivo y debería haberse solucionado el problema 👍
