### ISSUE TITLE
Erro de CORS na instância de objeto Mercado Pago

### ISSUE THREAD

**Issue by p-h-marques** [mercadopago/sdk-js#25]
**Descrição**
Olá! Ao instanciar o objeto do Mercado Pago, a página faz algumas requisições para `https://events.mercadopago.com/v2/traffic-light`, que retornam com erro de CORS.

**Meu código**
```html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Teste</title>
</head>
<body>
    <script src="https://sdk.mercadopago.com/js/v2"></script>

    <script src="scripts.js"></script>
</body>
</html>
```

```js
document.addEventListener('DOMContentLoaded', ()=>{
    const tokenMp = 'useiaquimeutoken'
    const mp = new MercadoPago(tokenMp);
})
```

![bug](https://user-images.githubusercontent.com/56172055/124126475-14bbf300-da51-11eb-9759-980238507d03.png)

Gostaria de verificar o porquê desse erro de CORS, e corrigí-lo se possível.

- Browser: Vivaldi | 4.0.2312.33 (Stable channel) (64 bits)

**Comment by NicholasPedroso** [comment]
Olá @p-h-marques tudo bem?

Agora mesmo vamos investigar este erro de CORS e retorno assim que tiver alguma posição.

Obrigado

**Comment by eduardotomassiwakapi** [comment]
Hi everyone. 
I am having the same issue with cors on chrome
![image](https://user-images.githubusercontent.com/66016615/124130319-066fd600-da55-11eb-9296-7ae5ff2540d5.png)
![image](https://user-images.githubusercontent.com/66016615/124130474-34551a80-da55-11eb-8f9d-2fb7b5972087.png)

**Comment by NicholasPedroso** [comment]
@p-h-marques conseguimos identificar e solucionar o problema :)

Muito obrigado por nos avisar!

Ficamos à disposição

@eduardotomassiwakapi we have already identified and solved this issue.

Thank you so much for letting us know!

Cheers

**Comment by p-h-marques** [comment]
Belezura, aqui o erro não está mais ocorrendo. Muito obrigado!

**Comment by eduardotomassiwakapi** [comment]
Thank you very much man
