### ISSUE TITLE
mp.createCardToken() not working

### ISSUE THREAD

**Issue by Pgovalle** [mercadopago/sdk-js#26]
**Describe the bug**
mp.createCardToken is giving me the following error:
{
code: "E601"
description: "an error occurred doing POST card_token"
}

**To Reproduce**
Just running the example:
```
const cardToken = await mp.createCardToken({
        cardNumber: '5031433215406351',
        cardholderName: 'APRO',
        cardExpirationMonth: '11',
        cardExpirationYear: '2025',
        securityCode: '123',
        identificationType: 'CPF',
        identificationNumber: '12345678912',
});
```

**Comment by NicholasPedroso** [comment]
Hi @Pgovalle 

I was able to reproduce the error and in fact there is an instability in this endpoint that is called when invoking this method.

This instability **does NOT affect production**, only test credentials.

We're working on it to fix it as soon as possible,

Thanks for opening the issue

**Comment by NicholasPedroso** [comment]
The issue has been detected and the fix is now in production.
Everything should be going fine by now.

If you still have any problem with it, don't hesitate to reopen this issue,

thanks
