### ISSUE TITLE
CardForm amount param invalid type

### ISSUE THREAD

**Issue by bhfaria** [mercadopago/sdk-js#3]
In the document the amount param is setted to receive a string value.

In debug mode an error was triggered: "Type of amount must be number. Received string"

If I use float numbers the form is not mounted. Is accepting only integer numbers.

**Comment by NicholasPedroso** [comment]
Hi @bhfaria,

Thanks for your support, indeed we had a issue with the amount type. We now fixed and `amount` param is expecting a string, i.e: to charge $100,50 you should use 
```javascript
{
...
    amount: '100.5'
...
}
```

We appreciate your time,

Thanks
