### ISSUE TITLE
Error: MercadoPago.js

### ISSUE THREAD

**Issue by George2215** [mercadopago/sdk-js#30]
**Describe the bug**
Estoy intentando intregrar pagos con tarjetas, y me guio con la documentacion publicada para tal fin, pero estoy obteniendo el siguiente mensaje:

Error: MercadoPago.js - Could not find HTML element for provided id: form-checkout

**To Reproduce**
Implementar el formulario según documentación
[Documentación](https://www.mercadopago.cl/developers/es/guides/online-payments/checkout-api/receiving-payment-by-card)

**Expected behavior**
Renderizar el formulario de forma correcta.

**Environment (please complete the following information):**

- Browser: [e.g. Chrome/Firefox]

Agradezco la orientación para solucionar el inconveniente.

**Comment by lucmantovani** [comment]
Hola @George2215!

Este error ocurre cuando el componente CardForm no puede encontrar el formulario con la identificación definida en el campo form.id. En su caso, por la mensaje de error el id debería ser "form-checkout"

Esto puede suceder cuando los identificadores son diferentes (en input id y form.id) o cuando el elemento HTML aún no se ha creado (código HTML después de JS).

**Comment by George2215** [comment]
@lucmantovani , Muchas gracias por la observación, efectivamente en el id me faltaba una letra...
