### ISSUE TITLE
CORS error when opening the checkout modal

### ISSUE THREAD

**Issue by lucasexe** [mercadopago/sdk-js#35]
Hi,

**Describe the bug**
I'm facing the following errors when I click to open the checkout modal:

![image](https://user-images.githubusercontent.com/25232221/134786278-f9462621-666b-4881-8694-b7ec03fed16a.png)

![image](https://user-images.githubusercontent.com/25232221/134786653-5eec5a30-44f0-44b0-a776-603f61e98706.png)

![image](https://user-images.githubusercontent.com/25232221/134786699-415f966e-ef62-415c-9527-cb4c50870b1e.png)

Those errors don't affect the checkout's functionality but I've found another problem and I believe it has the same root cause:
Some payments by credit cart are tagged as suspected and need to validate the data. Then, the checkout shows a button to start reviewing the data. When clicking on it, the checkout's frame is blocked, saying that the request was rejected. 

**To Reproduce**
```
<script src="https://sdk.mercadopago.com/js/v2"></script>
<script>
const mp = new MercadoPago('MY_PUBLIC_KEY', {
            locale: 'pt-BR'
    });
// ...
$("#myForm").submit(function() {
   // some checks
  // ...
  openCheckout();
});

function openCheckout() {
    const checkout = mp.checkout({
        preference: {
            id: PREFERENCE_ID
        },
        autoOpen: true,
    });
}
</script>
```

**Expected behavior**
No CORS errors.

**Environment (please complete the following information):**

- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36

**Additional context**

Thanks.

**Comment by Kneehole** [comment]
Hi @lucasexe! We really apreciate your feedback. The issue you are trying to troubleshoot about fraud's rejections, it's not related with that CORS issue reported on console. Can you provide us more information/screenshots about that problem of data validation's steps

Besides that, I let you know we are already working on, to solve that script CORS bug 

Thanks for all your feedback!

**Comment by lucasexe** [comment]
Hi @Kneehole
I'll open another issue describing the problem in the fraud's rejections. Thanks

About the CORS:

My form is:
```
<form class="container precheckout" action="" method="POST">
	<input type="hidden" name="action" value="preference">
	<div class="row">
		<div class="col-lg-12">
			<div class="section-title">
				<h3>Você está quase lá!</h3>
			</div>
		</div>
	</div>
	<div class="most__search__tab mb-4">
		<ul class="nav nav-tabs" role="tablist">
		</ul>
	</div>
	<h4 class="mb-4">Informe a lista de participantes:</h4>
	<div class="row">
		<div class="col-12 mb-3 mt-2">
			<strong>evento teste - Setor caro</strong>
		</div>
		<div class="col-12 col-md-6 form-group">
			<label for="name_3_1244654830">Nome do 1º participante</label>
			<input value="" placeholder="Nome do participante" id="name_3_1244654830" name="name_3_1244654830" type="text" required class="form-control">
		</div>
		<div class="col-12 col-md-6 form-group">
			<label for="docPart_3_1244654830">Documento com foto do 1º participante</label>
			<input value="" placeholder="Número do RG, CNH, etc." id="docPart_3_1244654830" name="docPart_3_1244654830" type="text" required class="form-control">
		</div>
	</div>
	<div class="mt-4">
		<label><input type="checkbox" id="checked" required name="checked"> <strong>Todos os dados foram revisados e estão corretos. </strong></label>
	</div>
	<div class="checkout_payment">
		<button type="submit" class="site-btn btn-block mt-1"> Continuar </button>
	</div>
</form>
```

My function is:
```
function openExternalCheckout() {
    const checkout = mp.checkout({
        preference: {
            id: window.preferenceId
        },
        autoOpen: true,
    });
}

window.preferenceId = null;
$("form.precheckout").on('submit', function(e) {
    e.preventDefault();
    if (!formValidator.form()) return false;
    if (window.preferenceId) {
        openExternalCheckout();
        return false;
    }
    Swal.showLoading();
    var form = $(this);
    $.ajax({
        type: form.attr('method'),
        url: form.attr('action'),
        data: form.serialize(),
    }).done(function(data) {
        Swal.close();
        if (!data || !data.id) {
            Swal.fire({type: 'error', icon: 'error', title: 'Algo deu errado', text: data.error || 'Por favor tente novamente.' });
            return;
        }
        window.preferenceId = data.id;
        openExternalCheckout();
    }).fail(function() {
        Swal.close();
        Swal.fire({type: 'error', icon: 'error', title: 'Algo deu errado', text: 'Por favor tente novamente.' });
    });
    return false;
});
```

If you need any other data, please let me know.

Thanks

**Comment by NicholasPedroso** [comment]
Hi, this problem should be solved by now.
Closing the issue
