### ISSUE TITLE
Divergência na documentação

### ISSUE THREAD

**Issue by bhfaria** [mercadopago/sdk-js#4]
No createCardToken há vários parametros, dentre eles **cardholderIdentificationType** e **cardholderIdentificationNumber**

Ocorre que no javascript os parametros são outros: **docType** e **docNumber**

Por eu não ter experiência com github para subir alterações, solicito, se possível, corrigir a documentação.

```
const cardToken = await mp.createCardToken({
    cardNumber: '5031433215406351' ,
    cardholderName: 'APRO',
    cardholderIdentificationType: 'CPF',
    cardholderIdentificationNumber: '12345678912',
    securityCode: '123',
    cardExpirationMonth: '11',
    cardExpirationYear: '2025',
})
```

**Comment by NicholasPedroso** [comment]
Olá @bhfaria , 

muito boa sua observação, já fiz as alterações e agora a propriedade `cardForm.form` é aceita com as mesmas propriedades que o `createCardToken` mantendo assim a consistência.

Vale lembrar que quando se utiliza o cardForm não é necessário passar os parametros no momento de criar o token, basta utilizar `cardForm instance.createCardToken()` pois o o SDK já tem mapeado internamente os campos necessários.

Muito obrigado pela sua contribuição
