### ISSUE TITLE
mp.createCardToken returning "not found" tokens

### ISSUE THREAD

**Issue by imarquezc** [mercadopago/sdk-js#40]
**Describe the bug**
Estoy integrando suscripciones de mercadopago en mi website.
En el front uso `createCardToken` y me devuelve un objecto.

En el backend, al usar el id del objeto como `card_token_id` obtengo de vuelta `{"message"=>"Card token service not found", "status"=>404}`

**To Reproduce**
Desde el front el request exacto es el siguiente:

```
POST https://api.mercadopago.com/v1/card_tokens?public_key=TEST-XXXXXXXXX057&locale=es-CL&js_version=2.0.0&referer=http://localhost:8080

{
	"card_number": "4509953566233704",
	"cardholder": {
		"identification": {},
		"name": "APRV"
	},
	"device": {...},
	"expiration_month": 11,
	"expiration_year": 2025,
	"security_code": "123"
}
```

y la response:

```
{
	"id": "7fc113ee3102728a416834c54ef16ac7",
	"public_key": "TEST-XXXXXXXXXXXXXXXXXXX",
	"first_six_digits": "450995",
	"expiration_month": 11,
	"expiration_year": 2025,
	"last_four_digits": "3704",
	"cardholder": {
		"identification": {},
		"name": "APRV"
	},
	"status": "active",
	"date_created": "2021-11-18T16:05:46.075-04:00",
	"date_last_updated": "2021-11-18T16:05:46.075-04:00",
	"date_due": "2021-11-26T16:05:46.075-04:00",
	"luhn_validation": true,
	"live_mode": false,
	"require_esc": false,
	"card_number_length": 16,
	"security_code_length": 3
}
```

Hasta ahí todo parece ir bien, 

pero luego al usar response.id como `card_token_id` al crear una suscripción, obtengo el error de not_found.

```
POST /preapproval

body: {
  "auto_recurring"=>{"currency_id"=>"CLP", "transaction_amount"=>"990.0", "frequency"=>1, "frequency_type"=>"months"},
 "back_url"=>"https://www.mercadopago.cl/",
 "collector_id"=>1006161850,
 "payer_email"=>"ignacio@getplutto.com",
 "reason"=>"Important reason",
 "card_token_id"=>"7fc113ee3102728a416834c54ef16ac7",
 "status"=>"authorized",
 "external_reference"=>"customer_8e9abd5caa7d99608e30ef3e"
}


Response:

{"message"=>"Card token service not found", "status"=>404}
```

Agradezco cualquier ayuda que pueda servir a continuar.
Gracias

**Comment by nicolassalvanes** [comment]
Hola, @imarquezc!

El problema que indicas no está puntualmente relacionado con la SDK, sino con la integración del producto suscripciones.

Si el error aún persiste, por favor recopile toda la información y envíela a nuestro equipo de soporte a desarrolladores para ayudarlo a resolverlo. En canal indicado es https://www.mercadopago.com/developers/es/support.

¡Muchas gracias por su contacto!

**Comment by imarquezc** [comment]
@nicolassalvanes muchas gracias por tu respuesta.
Traté de contactarlos hace varios días pero no he tenido respuesta.
Seguiré esperando, saludos!
