### ISSUE TITLE
DeviceProfile could not be loaded

### ISSUE THREAD

**Issue by SrBrahma** [mercadopago/sdk-js#41]
**Describe the bug**
I am using WebView in my React Native as I just don't like the native SDK and it doesn't seem to just allow tokenizing a card without making a checkout. My WebView loads an HTML I deployed via Firebase Hosting, that has HTTPS+SSL by default. The HTML just has the card form, the public token and the createCardToken(). It returns the token to RN via `window.postMessage()` and then I can proceed with my user cards / payment flow.

It works flawlessly in a normal browser with both dev and prod public tokens, but on the WebView, it warns `"DeviceProfile could not be loaded"`. Only happens with prod public token.

I am aware that MP doesn't support React Native by default (and I see that as a mistake), but looks like I got everything working besides this warn. If this gets fixed (and I would be a proof that it's possible to get it working), then it's a big market that MP can start to take from Stripe in Latin America.

Apparently this warn will only happen if advancedFraudPrevention is true, so maybe I can just turn it to false to get it working for my case.

Also, as I am guessing, MP server checks some header when making the POST to `/devices/widgets` and verify if the device is known. Maybe it would only be a matter of adding to the whitelist whatever WebView uses as an identifier.

The WebView allows setting some configurations, so maybe if I know what I have to add to it there is nothing to be done by MP. https://github.com/react-native-webview/react-native-webview

The unminified sdk MP code of this warn is:

```js
try {
    const { advancedFraudPrevention: e } = Ct(this, St);
    if (!e) return Promise.resolve();
    const t = await (async () => {
        try {
            const e = await L.fetch("/devices/widgets", { method: "POST", body: JSON.stringify({ section: "open_platform_V2", view: "checkout" }) }),
                t = await e.json(),
                n = document.createElement("script");
            return n.appendChild(document.createTextNode(t.widget.replace(/<script\b[^<]*">/gi, "").replace(/<\/script>[\s\S]*/gi, ""))), document.head.appendChild(n), Promise.resolve(t.session_id);
        } catch (e) {
            return Promise.reject(e);
        }
    })();
    return r.i.setDeviceProfile(t), Promise.resolve();
} catch (e) {
    return console.warn("DeviceProfile could not be loaded", e), Promise.resolve();
}
```

**To Reproduce**

- Setup a React Native project
- Install react-native-webview
- Have a <WebView/> component with

```jsx
<WebView
  scalesPageToFit
  incognito
  cacheEnabled={false}
  originWhitelist={['https://*']}
  source={{ uri: 'https://myappname-firebase.web.app' }}
/>
```
- Use Prod token, test card, and on the HTML call the createCardToken(). No need to setup a form, just a button with the createCardToken({...testCardData})
- I can provide further reproduction and debug info if someone is going to reproduce it, but it's mainly this.

**Expected behavior**
Should work without warns when using sdk in a WebView.

**Environment (please complete the following information):**

- "react-native-webview": "^11.15.0"

**Comment by NicholasPedroso** [comment]
Hello @SrBrahma , how are you?

Thanks for the very detailed issue. In fact, there shouldn't be a reason for this error with Device Profile to occur. The Device Profile script is responsible for helping in fraud prevention, and consequently in payment approval. It is not mandatory, and as you said, it can be turned off with the `advancedFraudPrevention` flag, but it is super important to keep it, so the payments approval stays high.

For these cases, where there are some issues with integration, I encourage you to forward this issue to our [support channel](https://www.mercadopago.com/developers/en/support). I am sure they will help you with your integration.

Thanks

**Comment by SrBrahma** [comment]
The support Adriano said they only support the listed platforms and closed the ticket.

**Comment by NicholasPedroso** [comment]
Hi @SrBrahma how are you?
Sorry for the delay. In fact, this scenario is not considered for our integrations. Anyway, it still intrigues me why it's not working. I don't see any clear reason why it shouldn't work. Maybe it's a particular case of your integration?

Have you made any progress with it?

Thanks,

**Comment by SrBrahma** [comment]
I can only guess that WebView sends or don't some specific header in HTTP requests that doesn't satisfy the `/devices/widgets` endpoint. As I don't have access to the code of this endpoint, I don't have further clues on what it may be.

I am now using Stripe as I needed to have a working gateway for my project.

**Comment by NicholasPedroso** [comment]
I'm sorry you had this experience with our integration. I have already forwarded your case internally so that we can support this type of issue in the future.

I'm closing this issue,

Thanks again, have a nice day
