### ISSUE TITLE
Me ajuda ai vai

### ISSUE THREAD

**Issue by ratozumbi** [mercadopago/sdk-js#42]
Eu não aceito que que eu tenha que enviar uma foto da minha identidade para o mercado pago, porém não consigo deletar minha conta sem enviar essa informção. Não encontro nenhuma opção de ajuda relativa ao meu problema. Me ajuda ai, manda a minha mensagem pro seu superior? brunowillianandrade@gmail.com

**Comment by biaguerreiromeli** [comment]
@ratozumbi Olá, Bruno! Tudo bem com você? 

O protocolo KYC (_[know your client](https://kycbrasil.com/conceito/)_) faz parte da política de segurança de prova de vida e comprovação de identidade do Mercado Pago, e é ele quem nos ajuda na prevenção de riscos e fraudes! 

Este canal, entretanto, é destinado a questões técnicas do produto e não tem qualquer envolvimento com as políticas de segurança adotadas pela empresa. 

Caso você deseje registrar a sua insatisfação com o protocolo usado, peço que abra um ticket ao nosso time oficial de suporte [aqui](https://www.mercadopago.com.br/developers/pt/support)!

Obrigada por entrar em contato conosco e compartilhar o seu feedback! 
Estamos em beta contínuo para promover a melhor experiência do mercado 🚀
