### ISSUE TITLE
An error occurred doing POST card_token

### ISSUE THREAD

**Issue by juliocesar757** [mercadopago/sdk-js#44]
Describe the bug:

mp.createCardToken return the following error: { code: "E603" description: "an error occurred doing POST card_token" }

To reproduce running the example:

const cardToken = await mp.createCardToken({ cardNumber: '375365153556885', cardholderName: 'APRO', cardExpirationMonth: '11', cardExpirationYear: '25', securityCode: '1234', identificationType: 'CPF', identificationNumber: '12345678910', });

**Comment by NicholasPedroso** [comment]
Hi @juliocesar757 ,
I tried the exactly same code and it went well, without any errors.

![image](https://user-images.githubusercontent.com/8353990/147566860-4cffcbaf-5224-463f-a258-b8015b0ae418.png)

Could you confirm me if the error still persists?

Thanks

**Comment by juliocesar757** [comment]
Hello @NicholasPedroso 

The error is intermittent.
Sometimes you get the token on the first API call. Sometimes I need to redo the call to get the token without the E603 error.

![prints-error-603](https://user-images.githubusercontent.com/49540652/147569462-cc5e0c3f-a912-458f-8563-91116d2277d6.png)

**Comment by juliocesar757** [comment]
@NicholasPedroso 

Second try, it worked without errors.

![prints-error-603-console-2](https://user-images.githubusercontent.com/49540652/147571435-53d4cbe8-715d-4e82-8e6c-c49fe60d93b7.png)

**Comment by NicholasPedroso** [comment]
Hi @juliocesar757 

Thanks for the info, I'm working on it and I'll let you know when I get some status on it.

**Comment by NicholasPedroso** [comment]
I'm closing this issue as it is related to issue #43
