### ISSUE TITLE
Reemplaza el objeto `exports`.

### ISSUE THREAD

**Issue by gquagliano** [mercadopago/sdk-js#6]
**Describe the bug**
En `https://secure.mlstatic.com/sdk/javascript/v1/mercadopago.js`, descomprimido con el inspector de WebKit línea 622, el script crea la variable global `exports`. Esta variable es utilizada por librerías compatibles con Node.js y puede producir errores.

Es discutible si las otras librerías deberían fiarse de la suposición de que `exports` no estará definido (o será indefinido) en navegador web, pero en cualquier caso, esto en particular entiendo que no es intencional y debería mantenerse dentro de su contexto.

**To Reproduce**
Incluir el API de MercadoPago y luego una librería como Slick (https://kenwheeler.github.io/slick/).

**Expected behavior**
No deberían producirse errores.

**Environment (please complete the following information):**

- Browser: Opera 74.0.3911.218

**Additional context**
No.

**Comment by NicholasPedroso** [comment]
¿Hola todo bien?

Muchas gracias por resaltar este error. Vamos a implementar una solución para arreglarlo.

Tan pronto como tengamos la solución en producción, se lo haremos saber.

**Comment by NicholasPedroso** [comment]
Hola @gquagliano ,

El equipo analizó este reporte e identificó que nuestra última versión de la SDK no presenta este bug.

Le recomendamos probar con la [versión 2](https://sdk.mercadopago.com/js/v2) y continuar el desarrollo mirando la [documentación actualizada](https://www.mercadopago.com.ar/developers/es/guides/online-payments/checkout-api/v2/receiving-payment-by-card)

Gracias
