### ISSUE TITLE
Can't load SDK-v2 to the page

### ISSUE THREAD

**Issue by denisglindep** [mercadopago/sdk-js#7]
**Describe the bug**
- `Error: GET https://sdk.mercadopago.com/js/v2 net::ERR_TOO_MANY_REDIRECTS`

**To Reproduce**
- Add SDK-v2 to the page

- Code sample that fails
```js const script = document.createElement('script');
      script.src = 'https://sdk.mercadopago.com/js/v2';
      script.id = 'mercado-pago-sdk-script';
      document.body.appendChild(script); ```

**Expected behavior**
- Expect script successfully added to the page;

**Environment (please complete the following information):**
- Version 89.0.4389.114 (Official Build) (x86_64)

**Comment by NicholasPedroso** [comment]
Hi @denisglindep 

We are experiencing some problems in our infrastructure and we are working to resolve this issue as soon as possible.

Thank you for reporting this issue.

**Comment by NicholasPedroso** [comment]
Hi,

we are online again.

Thanks
