### ISSUE TITLE
Mobile Checkout

### ISSUE THREAD

**Issue by MartinUgarte** [mercadopago/sdk-js#8]
Hola buenas noches, es posible integrar esta libreria en una app movil? Muchas gracias!

**Comment by MartinUgarte** [comment]
Si es asi, que método recomiendan? Checkout Pro, Web Tokenize..

Saludos!

**Comment by NicholasPedroso** [comment]
Hola @MartinUgarte ,

La libreria MercadoPago.js fue hecha para aplicaciones web (clientside). Si su aplicación se ejecuta en una webview, debería funcionar.

Para checkouts nativos, tenemos nuestros SDKs oficiales para [Android](https://github.com/mercadopago/px-android) y para [iOS](https://github.com/mercadopago/px-ios)

Para poder ayudarte con más consultas sobre este tema, por favor contáctanos desde nuestro [canal de soporte](https://www.mercadopago.com.ar/developers/es/support) para que podamos responderte cuantos antes.


Gracias

**Comment by SrBrahma** [comment]
@NicholasPedroso , I am an Expo / React Native user. I want to make my own UI (without webview). As the client requires an SSL certificate, I want to tokenize the card, send it to my https server (Firebase Cloud Functions, has SSL integrated) and from there, it will comunicate to Mercado Pago.

Can I use the https://sdk.mercadopago.com/js/v2 without it being a browser? Apparently I will only need to use the tokenize() function.

**Comment by NicholasPedroso** [comment]
Hello @SrBrahma ,
the JS SDK is meant to be used in the browser and the sdk-nodejs can only be run in the backend (nodeJS).

For native checkouts, take a look at our official SDKs for [Android](https://github.com/mercadopago/px-android) and [iOS](https://github.com/mercadopago/px-ios)

For questions about integrations and more, I suggest you contact our [support channel.](https://www.mercadopago.com/developers/en/support)

Greetings
