### ISSUE TITLE
There is no button `Stay on site` when payment finished

### ISSUE THREAD

**Issue by denisglindep** [mercadopago/sdk-js#9]
**Describe the bug**
When I open `Checkout PRO` modal in case when backend created a preference without `back_urls\auto_return` specified, finish a payment and on success-screen - there is no `Stay on site` button, so I can't close a modal;

**To Reproduce**
1) On backend create a preference but not include fields `back_urls/auto_return`;
2) On frontend - receive a preference id, then include a library to the page.
3) Create a new checkout object but not include render-options;
4) Open checkout manually with `checkout.open()` method;
5) Finish a payment;
6) There is no `Stay on site` button;

- Code sample that fails
```js
  const script = document.createElement('script');
  script.src = 'https://sdk.mercadopago.com/js/v2';
  document.body.appendChild(script);
  script.addEventListener('load', () => {
    const mp = new window.MercadoPago('YOUR_PUBLIC_KEY');
    const checkout = mp.checkout({
      preference: {
        id: preference
      },
      openMode: 'modal',
    });
  
    checkout.open();
  });
```

**Expected behavior**
When preference created without `back_urls/auto_return` specified, I expect to receive a `preference_id`, create a new checkout, open it manually with `.open()`, finish payment, click `Stay on site` button, receive `message` event from Mercadopago iframe with `payment_status`.

**Environment (please complete the following information):**

- Browser: [e.g. Chrome/Firefox/Safari/IE11]
89.0.4389.114 (Official Build) (x86_64)

**Comment by estefaniadiazartucio** [comment]
Hi @denisglindep ! 
We've analyzed your issue with the `Stay on site` button not showing  up and it seems to be related to a bug. The cause has been already identified and we'll be releasing the fix as soon as possible.
Regarding the events though, they're not yet supported. In this case we recommend configuring `back_urls` in your preference to be able to receive the `payment_status` information when being redirected back to the site.

**Comment by NicholasPedroso** [comment]
Hello @denisglindep ,

the bug fix is already productive. Thank you for reporting it
